config/routes.rb
Rails.application.routes.draw do
  get 'show/diploma'

  get 'create/diploma'

  get 'translate/diploma'

  get 'welcome/index'
  root 'translate#diploma'

  get 'translate', to: 'translate#diploma'
  get 'create', to: 'create#diploma'
  get 'show', to: 'show#diploma'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/create_controller.rb
class CreateController < ApplicationController
  def diploma
  end
end

app/controllers/show_controller.rb
class ShowController < ApplicationController
  def diploma
  end
end

app/controllers/translate_controller.rb
class TranslateController < ApplicationController
  def diploma
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/create_helper.rb
module CreateHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/translate_helper.rb
module TranslateHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/create/diploma.html.erb
<div class='container' style='width: 750px; padding-top: 10px;'>

			<div class='row'>
				<div class='col-md-6' style='padding-left: 40px;'><a name='заказать дипломную работу'><h6><b>Создание ПО(программное обеспечение)</b></h6></a></div>
			</div>

			<div class='row' style='padding-left: 30px;'>
				<div class='col-md-4'><a name='создать дипломную работу'><h6><b>Создать мобильное приложение iOS</b></h6></a></div>
			</div>

			<div class='row' style='padding-left: 40px;'>
				<div class="col-md-3"><h6>Количество окон</h6></div>
	  			<div class="col-md-2"><h6>Цена</h6></div>
	  			<div class="col-md-2"><h6>Сроки</h6></div>
	  			<div class="col-md-2"><h6>Ускорение</h6></div>
			</div>

			<div class='row' style='padding-left: 40px;'>
				<div class="col-md-3"><h6>до 3 окон</h6></div>
	  			<div class="col-md-2"><h6>55 000 тенге</h6></div>
	  			<div class="col-md-2"><h6>4-5 дней</h6></div>
	  			<div class="col-md-2"><h6>10 000 тенге</h6></div>
			</div>

			<div class='row' style='padding-left: 40px;'>
				<div class="col-md-3"><h6>до 5 окон</h6></div>
	  			<div class="col-md-2"><h6>59 000 тенге</h6></div>
	  			<div class="col-md-2"><h6>4-5 дней</h6></div>
	  			<div class="col-md-2"><h6>10 000 тенге</h6></div>
			</div>

			<div class='row' style='padding-left: 40px;'>
				<div class="col-md-3"><h6>до 7 окон</h6></div>
	  			<div class="col-md-2"><h6>65 000 тенге</h6></div>
	  			<div class="col-md-2"><h6>4-5 дней</h6></div>
	  			<div class="col-md-2"><h6>10 000 тенге</h6></div>
			</div>









			<div class='row' style='padding-left: 30px;'>
				<div class='col-md-4'><a name='создать дипломную работу'><h6><b>Создать мобильное приложение Android</b></h6></a></div>
			</div>

			<div class='row' style='padding-left: 40px;'>
				<div class="col-md-3"><h6>Количество окон</h6></div>
	  			<div class="col-md-2"><h6>Цена</h6></div>
	  			<div class="col-md-2"><h6>Сроки</h6></div>
	  			<div class="col-md-2"><h6>Ускорение</h6></div>
			</div>

			<div class='row' style='padding-left: 40px;'>
				<div class="col-md-3"><h6>до 3 окон</h6></div>
	  			<div class="col-md-2"><h6>55 000 тенге</h6></div>
	  			<div class="col-md-2"><h6>4-5 дней</h6></div>
	  			<div class="col-md-2"><h6>10 000 тенге</h6></div>
			</div>

			<div class='row' style='padding-left: 40px;'>
				<div class="col-md-3"><h6>до 5 окон</h6></div>
	  			<div class="col-md-2"><h6>59 000 тенге</h6></div>
	  			<div class="col-md-2"><h6>4-5 дней</h6></div>
	  			<div class="col-md-2"><h6>10 000 тенге</h6></div>
			</div>

			<div class='row' style='padding-left: 40px;'>
				<div class="col-md-3"><h6>до 7 окон</h6></div>
	  			<div class="col-md-2"><h6>65 000 тенге</h6></div>
	  			<div class="col-md-2"><h6>4-5 дней</h6></div>
	  			<div class="col-md-2"><h6>10 000 тенге</h6></div>
			</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diploma Docs - заказ дипломной работы</title>
  <meta name="description" content="заказать дипломную работу в алматы" />
  <meta name="google-site-verification" content="dMSOy_7Ito0dZ2zD5_10soPuXg5Rbg84f189ch-I_EY" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='container' style='width: 700px;'>
	<div class='row' style='padding-top: 5px;'>
		
		<div class='col-md-3' style='padding-top: 15px;'><a name="Заказать дипломную работу"><b><%= link_to 'Дипломные работы', translate_diploma_path %></b></div>
		<div class='col-md-1' style='padding-top: 13px;padding-left: 150px;'><%= image_tag("contact.png", :size => "25x25") %></div>
		<div class='col-md-3' style='padding-top: 11px;'><h6><b>+7 775 7721688</b></h6></div>			
	</div>
	<div class='row'>
				<div class='col-md-1' style='width: 70px; padding-top: 15px;'><h6><b>Город: </b></h6></div>
				<div class='col-md-2' style='padding-top: 15px;'>
					<marquee scrollamount="5" direction="left" height='30px' pad>
								<h6><b>
								Акколь &nbsp;
								Аксай &nbsp;
								Аксу &nbsp;
								Актау &nbsp;
								Алга &nbsp;
								Аркалык &nbsp;
								Астана &nbsp;
								Аягоз &nbsp;
								Байконыр &nbsp;
								Экибастуз &nbsp;
								Есик &nbsp;
								Есиль &nbsp;
								Хромтау &nbsp;
								Кандыагаш &nbsp;
								Караганда &nbsp;
								Каратау &nbsp;
								Каркаралинск &nbsp;
								Кокшетау &nbsp;
								Костанай &nbsp;
								Кульсары &nbsp;
								Курчатов &nbsp;
								Кызылорда &nbsp;
								Лисаковск &nbsp;
								Павлодар &nbsp;
								Петропавловск &nbsp;
								Риддер &nbsp;
								Рудный &nbsp;
								Сарань &nbsp;
								Шемонаиха &nbsp;
								Чу &nbsp;
								Степногорск &nbsp;
								Шымкент &nbsp;
								Талдыкорган &nbsp;
								Талгар &nbsp;
								Тараз &nbsp;
								Текели &nbsp;
								Темиртау &nbsp;
								Туркестан &nbsp;
								Уральск &nbsp;
								Усть-Каменогорск &nbsp;
								Жанаозен &nbsp;
								Жаркент &nbsp;
								Жезказган &nbsp;
								Житикара &nbsp;
								Зыряновск &nbsp;
								</b></h6>
					</marquee>
				</div>
	</div>
</div>

<div class='container' style='width: 700px; padding-top: 5px;'>
	<div class='row' style='padding-top: 5px;'>
		<div class='col-md-3'><a name='Перевод дипломной работы'><h6><b><%= link_to 'Перевод дипломной работы', translate_diploma_path %></b></h6></a></div>
		<div class='col-md-3'><a name='Разработка дипломной работы'><h6><b><%= link_to 'Разработка дипломной работы', create_diploma_path %></b></h6></a></div>
		<div class='col-md-3'><a name='Презентация дипломной работы'><h6><b><%= link_to 'Презентация дипломной работы', show_diploma_path %></b></h6></a></div>
	</div>
</div>

<%= yield %>

<div class='container' style='width: 700px; padding-top: 5px;'>
	<div class='row' style='padding-top: 5px;'>
		<div style='width: 500px; padding-top: 3px; padding-left: 10px;'><h6><b>Cо стороны разработчиков в обязательном порядке сообщается уведолмение об изменении(ях)</b></h6></div>
	</div>
</div>

</body>
</html>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-56116735-3', 'auto');
  ga('send', 'pageview');

</script>

app/views/show/diploma.html.erb
<div class='container' style='width: 750px; padding-top: 10px;'>

			<div class='row'>
				<div class='col-md-6' style='padding-left: 40px;'><a name='презентация дипломной работы'><h6><b>Создание презентации в заданном формате</b></h6></a></div>
			</div>

			<div class='row' style='padding-left: 30px;'>
				<div class='col-md-4'><a name='Adobe Illustrator'><h6><b>Создать презентацию на Adobe Illustrator</b></h6></a></div>
			</div>

			<div class='row' style='padding-left: 40px;'>
				<div class="col-md-3"><h6>Количество слайдов</h6></div>
	  			<div class="col-md-2"><h6>Цена</h6></div>
	  			<div class="col-md-2"><h6>Сроки</h6></div>
	  			<div class="col-md-2"><h6>Ускорение</h6></div>
			</div>

			<div class='row' style='padding-left: 40px;'>
				<div class="col-md-3"><h6>до 10 слайдов</h6></div>
	  			<div class="col-md-2"><h6>55 000 тенге</h6></div>
	  			<div class="col-md-2"><h6>4-5 дней</h6></div>
	  			<div class="col-md-2"><h6>10 000 тенге</h6></div>
			</div>

			<div class='row' style='padding-left: 40px;'>
				<div class="col-md-3"><h6>до 15 слайдов</h6></div>
	  			<div class="col-md-2"><h6>59 000 тенге</h6></div>
	  			<div class="col-md-2"><h6>4-5 дней</h6></div>
	  			<div class="col-md-2"><h6>10 000 тенге</h6></div>
			</div>

			<div class='row' style='padding-left: 40px;'>
				<div class="col-md-3"><h6>до 20 слайдов</h6></div>
	  			<div class="col-md-2"><h6>65 000 тенге</h6></div>
	  			<div class="col-md-2"><h6>4-5 дней</h6></div>
	  			<div class="col-md-2"><h6>10 000 тенге</h6></div>
			</div>


			<div class='row' style='padding-left: 30px;'>
				<div class='col-md-4'><a name="Keynote"><h6><b>Создать презентацию на Keynote</b></h6></a></div>
			</div>

			<div class='row' style='padding-left: 40px;'>
				<div class="col-md-3"><h6>Количество слайдов</h6></div>
	  			<div class="col-md-2"><h6>Цена</h6></div>
	  			<div class="col-md-2"><h6>Сроки</h6></div>
	  			<div class="col-md-2"><h6>Ускорение</h6></div>
			</div>

			<div class='row' style='padding-left: 40px;'>
				<div class="col-md-3"><h6>до 10 слайдов</h6></div>
	  			<div class="col-md-2"><h6>55 000 тенге</h6></div>
	  			<div class="col-md-2"><h6>4-5 дней</h6></div>
	  			<div class="col-md-2"><h6>10 000 тенге</h6></div>
			</div>

			<div class='row' style='padding-left: 40px;'>
				<div class="col-md-3"><h6>до 15 слайдов</h6></div>
	  			<div class="col-md-2"><h6>59 000 тенге</h6></div>
	  			<div class="col-md-2"><h6>4-5 дней</h6></div>
	  			<div class="col-md-2"><h6>10 000 тенге</h6></div>
			</div>

			<div class='row' style='padding-left: 40px;'>
				<div class="col-md-3"><h6>до 20 слайдов</h6></div>
	  			<div class="col-md-2"><h6>65 000 тенге</h6></div>
	  			<div class="col-md-2"><h6>4-5 дней</h6></div>
	  			<div class="col-md-2"><h6>10 000 тенге</h6></div>
			</div>
</div>

app/views/translate/diploma.html.erb
<div class='container' style='width: 750px; padding-top: 10px;'>
	<div class='row'>
		<div class='col-md-4' style='padding-left: 40px;'><a name='перевод дипломной работы'><h6><b>Перевод дипломной работы</b></h6></a></div>
	</div>

	<div class='row' style='padding-left: 30px;'>
		<div class='col-md-4'><a name='перевод дипломной работы'><h6><b>Русский язык - Английский язык</b></h6></a></div>
	</div>

	
		<div class='row' style='padding-left: 40px;'>
			<div class="col-md-3"><h6>Количество страниц</h6></div>
  			<div class="col-md-2"><h6>Цена</h6></div>
  			<div class="col-md-2"><h6>Сроки</h6></div>
  			<div class="col-md-2"><h6>Ускорение</h6></div>
		</div>

		<div class='row' style='padding-left: 40px;'>
			<div class="col-md-3"><h6>50 страниц</h6></div>
  			<div class="col-md-2"><h6>35 000 тенге</h6></div>
  			<div class="col-md-2"><h6>4-5 дней</h6></div>
  			<div class="col-md-2"><h6>10 000 тенге</h6></div>
		</div>

		<div class='row' style='padding-left: 40px;'>
			<div class="col-md-3"><h6>70 страниц</h6></div>
  			<div class="col-md-2"><h6>49 000 тенге</h6></div>
  			<div class="col-md-2"><h6>4-5 дней</h6></div>
  			<div class="col-md-2"><h6>10 000 тенге</h6></div>
		</div>

		<div class='row' style='padding-left: 40px;'>
			<div class="col-md-3"><h6>90 страниц</h6></div>
  			<div class="col-md-2"><h6>63 000 тенге</h6></div>
  			<div class="col-md-2"><h6>4-5 дней</h6></div>
  			<div class="col-md-2"><h6>10 000 тенге</h6></div>
		</div>

		<div class='row' style='padding-top: 10px;padding-left: 30px;'>
			<div class='col-md-4'><a name='перевод дипломной работы'><h6><b>Английский язык - Русский язык</b></h6></a></div>
		</div>

	
		<div class='row' style='padding-left: 40px;'>
			<div class="col-md-3"><h6>Количество страниц</h6></div>
  			<div class="col-md-2"><h6>Цена</h6></div>
  			<div class="col-md-2"><h6>Сроки</h6></div>
  			<div class="col-md-2"><h6>Ускорение</h6></div>
		</div>

		<div class='row' style='padding-left: 40px;'>
			<div class="col-md-3"><h6>50 страниц</h6></div>
  			<div class="col-md-2"><h6>35 000 тенге</h6></div>
  			<div class="col-md-2"><h6>4-5 дней</h6></div>
  			<div class="col-md-2"><h6>10 000 тенге</h6></div>
		</div>

		<div class='row' style='padding-left: 40px;'>
			<div class="col-md-3"><h6>70 страниц</h6></div>
  			<div class="col-md-2"><h6>49 000 тенге</h6></div>
  			<div class="col-md-2"><h6>4-5 дней</h6></div>
  			<div class="col-md-2"><h6>10 000 тенге</h6></div>
		</div>

		<div class='row' style='padding-left: 40px;'>
			<div class="col-md-3"><h6>90 страниц</h6></div>
  			<div class="col-md-2"><h6>63 000 тенге</h6></div>
  			<div class="col-md-2"><h6>4-5 дней</h6></div>
  			<div class="col-md-2"><h6>10 000 тенге</h6></div>
		</div>


		<div itemscope itemtype="http://schema.org/Offer">
  <span itemprop="name">Blend-O-Matic</span>
  <span itemprop="price">$19.95</span>
  <span itemprop="availability">Available today!</span>
</div>


	
</div>

app/views/welcome/index.html.erb
<div class='container' style='width: 750px; padding-top: 10px;'>

			<div class='row'>
				<div class='col-md-6' style='padding-left: 40px;'><h6><b>Создание презентации в заданном формате</b></h6></div>
			</div>

</div>